[package]
name = "store"
version = "0.1.0"
edition = "2021"

[[example]]
name = "counter"
path = "examples/store/counter.rs"

[[example]]
name = "time"
path = "examples/selector/time.rs"

[[example]]
name = "until"
path = "examples/selector/delay.rs"


[dependencies]


[dev-dependencies]
futures-lite = "2.2.0"
tokio = {version = "1.36.0", features = ["full"]}
