[package]
name = "store"
version = "0.1.0"
edition = "2021"

[[example]]
name = "counter"
path = "examples/store/counter.rs"

[[example]]
name = "drop_handle"
path = "examples/cancel/drop_handle.rs"



[dependencies]
pin-project = "1.1.5"

[dev-dependencies]
futures-lite = "2.2.0"
tokio = {version = "1.36.0", features = ["full"]}